DROP TABLE IF EXISTS "USERS" CASCADE;

create table if not exists users (
user_id int not null generated by default as identity primary key,
last_name varchar(100),
first_name varchar(100),
patronymic varchar(100),
date_of_birth date,
email varchar(320)
);
